### ISSUE TITLE
Extensions & Workflows

### ISSUE THREAD

**Issue by Sytten** [caido/caido#501]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

This is the new system that we are building for plugins.
- [x]  **Phase 1:** we are building workflows that are a no-code solution with caido-provided building blocks. One the block is running Javascript, I just finished it yesterday. There will be 3 types of workflows: convert (replacing the current convert), passive (respond to event to identify issues) and active (triggered by a user action). We will provide output blocks to store and display data in predetermined ways.
- [ ] **Phase 2:** we will allow custom blocks to be added to the workflows. This is more vague, but we are thinking of using WASM in the backend. We will define an SDK to interact with the engine. That gives good liberty to the developers to chose a language. For interpreted languages like python we can compile CPython in WASM and run the scripts (it's a bit more complicated than that).
- [x] **Phase 3:** allow developers to build custom UI within the frontend and channel communication with the backend part of the plugin. This is far off, not really defined how it will work yet.

**Comment by Sytten** [comment]
We have now completed Phase 1

**Comment by Sytten** [comment]
Closing this as we now have a good plugin system, we will still work on workflows in other issues
