### ISSUE TITLE
Improve experience for frontend scripts

### ISSUE THREAD

**Issue by Sytten** [caido/caido#742]
### Community Note

- This is to track/discuss small things we can do to improve scripts development. For larger items (like a proper API), separate issues will be open.

### Current list

- Frontend
  - [ ] Expose version as a global read-only variable
  - [ ] Expose runtime (desktop, browser) as a global read-only variable
- Backend
  - [ ] Publish diff of the schema in this repository

**Comment by bebiksior** [comment]
Here are some of my ideas:

- It'd be awesome if we could just set the path to JS/CSS file instead of constantly copying and pasting new code into the Custom JS/CSS field
- Basic functions like `OnLoad` and `OnTabChange`
- Replay tab: would be great if the navigation tabs `c-tab-navigation__tab` had `session-id` attribute

**Comment by Sytten** [comment]
lets close that, not actionable
